### PR TITLE
Integrate db:migrate with db:drop

### PR DESCRIPTION
**Pull request by k911**
Fixed db:drop for windows, and integrated db:migrate with dropping previously imported collection.

### CODE REVIEW

**Comment by FieryCod** [comment]
@k911 As far as I know `--drop` drops only targeted collections. This solution is ok, but we still need a tool to drop entire database, that is why I'm partially agree with you. What do you think about adding `db:drop` just in case?

**Comment by k911** [comment]
@FieryCod for now it is not necessary, and good practices tells us that add only things that are necessary.

**Comment by FieryCod** [comment]
Could you add `db:drop` in the shape it was? Deleting this line is not necessary.

**Comment by FieryCod** [comment]
Seems that there is only 2 spaces before db:drop script while there should be 4.

**Comment by k911** [comment]
Confirmed working also for linux shells.

**Pull request merged**
