### PR TITLE
Adds newest swagger-ui

### PR DESCRIPTION
**Pull request by FieryCod**
Adds the newest `swagger-ui` which works well with `swagger-tools`. 
This version is only for development purposes in future we should adapt `swagger-ui` for our's needs by refactoring `swagger-ui` components. By merging that `PR` we will be sure that our `API` looks good in `swagger-ui`.

### CODE REVIEW

**Comment by k911** [comment]
Isn't dist somehow auto-generated? If yes it should be excluded from repository.

**Comment by FieryCod** [comment]
Yes dist is auto-generated by the `swagger-ui` repo. I've extracted all necessary files from the `dist` folder. `PR` is ready to be merged.

**Comment by FieryCod** [comment]
@k911 I agree that it should be on front-end. but while developing the back-end it is much more desirable to know how does the particular `yaml` file looks in `docs`. By doing so we will be sure that the docs look great. This code is absolutely necessary, because it is better to write good `yaml`'es at once rather than refactoring them all in the end of developing `backend`.

**Comment by k911** [comment]
Then it should be generated when wanted (via new command like `npm run docs`), or generated and enabled when running via `npm run debug`. I'm sure there is a proper way to resolve this problem, in more  elegant way.

**Comment by FieryCod** [comment]
@k911 Do you really want to spend thousand hours for `swagger-ui` to generate `dist` folder? There is no better, or more elegant way. You think why `swagger-tools` ships with the `dist` of `swagger-ui`? Let's consider the idea of building the `swagger-ui` on our own, there are 2 problems:
1. time
2. generated docs needs to be adapt to our needs ([look here](https://github.com/swagger-api/swagger-ui#swaggeruibundle))

**Comment by k911** [comment]
But Frontend works just fine, there is just no content

**Comment by FieryCod** [comment]
I'm gonna configure `swagger-ui` with authenticator, passportjs etc.. that is why It would be comfortable for me to work with this stuff in a single repo rather than jumping from one repo to another.

**Comment by zrebcu411** [comment]
I do not know the topic of `swagger-ui` well, but I think it can be placed in `back-end` temporarily.

**Pull request merged**
